global:
  scrape_interval: 5s

scrape_configs:
  # Metrics do OTel Collector export
  - job_name: "otel-collector"
    static_configs:
      - targets: ["otel-collector:8889"]

  # Metrics sinh ra tá»« trace (Tempo)
  - job_name: "tempo"
    static_configs:
      - targets: ["tempo:8889"]
